import os
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from backend.app.core.config import settings

def generate_pdf_report(candidate_name: str, primary_career: dict, top_recommendations: list, skill_analysis: dict, output_filename: str = "CareerCast_Report.pdf") -> str:
    os.makedirs(settings.REPORTS_DIR, exist_ok=True)
    filepath = os.path.join(settings.REPORTS_DIR, output_filename)
    
    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        textColor=colors.HexColor('#059669'),
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        textColor=colors.HexColor('#475569'),
        spaceAfter=15
    )
    
    section_heading = ParagraphStyle(
        'SectionHead',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=12,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )
    
    story = []
    
    # Title Banner
    story.append(Paragraph("CareerCast – AI Career Intelligence Report", title_style))
    story.append(Paragraph(f"Candidate: <b>{candidate_name}</b> | Generated by CareerCast AI Engine", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#10B981'), spaceAfter=15))
    
    # Primary Prediction Summary
    story.append(Paragraph("1. Primary Predicted Career Match", section_heading))
    role_name = primary_career.get('role', 'N/A')
    prob = primary_career.get('probability', 0)
    desc = primary_career.get('description', '')
    
    pred_data = [
        [Paragraph("<b>Target Role</b>", body_style), Paragraph(f"<b>{role_name}</b>", body_style)],
        [Paragraph("<b>Confidence Score</b>", body_style), Paragraph(f"<b>{prob}%</b>", body_style)],
        [Paragraph("<b>Role Overview</b>", body_style), Paragraph(desc, body_style)]
    ]
    t = Table(pred_data, colWidths=[130, 410])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 15))
    
    # Top Recommendations Table
    story.append(Paragraph("2. Top 5 Career Alternatives", section_heading))
    rec_headers = [Paragraph("<b>Career Role</b>", body_style), Paragraph("<b>Match Probability</b>", body_style), Paragraph("<b>Key Skills Required</b>", body_style)]
    rec_rows = [rec_headers]
    
    for item in top_recommendations:
        skills_str = ", ".join(item.get("required_skills", [])[:4])
        rec_rows.append([
            Paragraph(item.get("role", ""), body_style),
            Paragraph(f"{item.get('probability', 0)}%", body_style),
            Paragraph(skills_str, body_style)
        ])
        
    t_rec = Table(rec_rows, colWidths=[160, 110, 270])
    t_rec.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#ECFDF5')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#047857')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#D1D5DB')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_rec)
    story.append(Spacer(1, 15))
    
    # Skill Gap Summary
    story.append(Paragraph("3. Skill Gap & Learning Roadmap", section_heading))
    score = skill_analysis.get("match_score", 0)
    matched_skills = ", ".join(skill_analysis.get("matched_skills", []))
    missing_skills = ", ".join(skill_analysis.get("missing_skills", []))
    
    skill_data = [
        [Paragraph("<b>Skill Match Index</b>", body_style), Paragraph(f"<b>{score}% Match</b>", body_style)],
        [Paragraph("<b>Existing Skills</b>", body_style), Paragraph(matched_skills if matched_skills else "None matched", body_style)],
        [Paragraph("<b>Missing Skills to Acquire</b>", body_style), Paragraph(missing_skills if missing_skills else "All core skills present!", body_style)]
    ]
    t_skill = Table(skill_data, colWidths=[150, 390])
    t_skill.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t_skill)
    
    doc.build(story)
    return filepath
